### ISSUE TITLE
Centrifuge Build failing due to issues with centrifuge-build-bin

### ISSUE THREAD

**Issue by meridiajane** [DaehwanKimLab/centrifuge#283]
Hello, I'm running on Rocky Linux Version 9.0 with Python 3.9.10, and am trying to build an index using Centrifuge 1.0.4.2. 

Code:
```
./centrifuge-build \
    --threads 5 \
    --conversion-table seqid2taxid.map \
    --taxonomy-tree taxonomy/nodes.dmp \
    --name-table taxonomy/names.dmp \
    input-sequences.fna abfvh
```

Expected output: creation of cf files

Actual output:
Before manually adding centrifuge-build-bin:
```
Traceback (most recent call last):
  File "/local/storage/Programs/centrifuge-1.0.4.2/centrifuge-build", line 79, in <module>
    main()
  File "/local/storage/Programs/centrifuge-1.0.4.2/centrifuge-build", line 76, in main
    os.execv(build_bin_spec, argv)
FileNotFoundError: [Errno 2] No such file or directory
```
After manually adding a bin with touch (to determine if that was the missing file):
```
Traceback (most recent call last):
  File "/local/storage/meridia_misc/centrifuge_index/./centrifuge-build", line 80, in <module>
    main()
  File "/local/storage/meridia_misc/centrifuge_index/./centrifuge-build", line 77, in main
    os.execv(build_bin_spec, argv)
OSError: [Errno 8] Exec format error
```
I'm not entirely sure whether the bin file is supposed to be produced by the program (and is just not happening) or whether there's a step that I missed in preparation. I do know that the input files (seqid2taxid.map, taxonomy/nodes.dmp, taxonomy/names.dmp, and input-sequences.fna) are all present in the same directory as centrifuge-build.

**Comment by meridiajane** [comment]
Update! I tried to run this through a singularity container as opposed to running it in the server environment directly, and it seems to be working. I'm leaving this open because I think it could be helpful to know what could be missing/incorrect in the environment.

Container obtained here:
`singularity pull https://depot.galaxyproject.org/singularity/centrifuge:1.0.4.2--hdcf5f25_0`
